# Application
app:
  name: nodejs-app
  namespace: api

# Container
image:
  repository: 688567278489.dkr.ecr.ap-southeast-1.amazonaws.com/nodejs-app
  tag: latest
  pullPolicy: Always

# Replicas
replicaCount: 2

# Container port
containerPort: 3000

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

# Health checks
healthCheck:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

# Service
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Ingress
ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  subnets: "subnet-089a938d1734752a9, subnet-01887dd5f48138636, subnet-03b08886c41a2e27c"
  healthCheckPath: /health
  host: "app.anjankumarpaul.com"
  certificateArn: "arn:aws:acm:ap-southeast-1:688567278489:certificate/ec17e461-0f3f-4aaf-bb51-b9509c00a093"
  sslRedirect: false

# HPA
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPU: 70
  targetMemory: 80

# Environment variables
env: {}
  # PORT: "3000"
  # NODE_ENV: "production"

# ConfigMap data
configMap:
  enabled: false
  data: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []